services:
  bajacloud:
    container_name: uofcbajacloud
    image:  darkicewolf50/uofcbajacloud:latest
    ports:
      - 8080:8000
    volumes:
      - ./L - Logistics/Interviews:/Interviews
    # networks:
    #   - testnet